# Generated by Django 2.0.3 on 2018-03-20 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_twitter', models.CharField(default='', max_length=256)),
                ('consumer_key', models.CharField(default='', max_length=256)),
                ('consumer_secret', models.CharField(default='', max_length=256)),
                ('access_token', models.CharField(default='', max_length=256)),
                ('access_token_secret', models.CharField(default='', max_length=256)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
