# Generated by Django 2.0.3 on 2018-04-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='perfiles',
        ),
    ]
