# Generated by Django 2.0.3 on 2018-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_perfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmcontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(default='', max_length=15)),
                ('texto', models.CharField(default='', max_length=256)),
                ('usuario', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
