# Generated by Django 2.0.3 on 2018-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('reduccion', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('reduccion', models.CharField(max_length=2)),
                ('continente', models.CharField(choices=[('America Norte', 'America Norte'), ('America Sur', 'America Sur'), ('America Central', 'America Central'), ('Asia', 'Asia'), ('Europa', 'Europa'), ('Oceania', 'Oceania'), ('Africa', 'Africa')], max_length=50)),
            ],
        ),
    ]
