# Generated by Django 2.0.3 on 2018-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_google', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paises',
            name='reduccion',
            field=models.CharField(max_length=5),
        ),
    ]
