# Generated by Django 2.0.3 on 2018-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_google', '0003_auto_20180502_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paises',
            name='continente',
            field=models.CharField(choices=[('America Norte', 'America Norte'), ('America Sur', 'America Sur'), ('America Central', 'America Central'), ('Asia', 'Asia'), ('Europa', 'Europa'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('Antartida', 'Antartida')], max_length=50),
        ),
    ]
