# Generated by Django 2.0.3 on 2018-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_google', '0004_auto_20180502_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='spider_html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=200)),
                ('subfiltro', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, editable=False)),
                ('hora', models.DateTimeField(blank=True, editable=False)),
                ('html', models.FileField(blank=True, upload_to='HTML/')),
            ],
        ),
    ]
