# Generated by Django 2.0.3 on 2018-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_google', '0005_spider_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider_html',
            name='fecha',
            field=models.CharField(editable=False, max_length=11),
        ),
        migrations.AlterField(
            model_name='spider_html',
            name='hora',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
